### ISSUE TITLE
cannot import config, service not starting

### ISSUE THREAD

**Issue by giorgiodidon** [jbruce12000/kiln-controller#45]
hi all, i'm sorry for the question, but i cannot start the kiln controller, i followed all steps but arrived to server startup (source venv/bin/activate; ./kiln-controller.py) it says cannot import config.py, may someone help me? 
thank you
giorgio

**Comment by iog-creator** [comment]
I tried it and yes it was set to simulate. But... Now it doesn't do
anything when I make a program and hit start. It doesn't do anything. Also
is it supposed to give you a temperature reading when not running? Mine
says 0

**Comment by giorgiodidon** [comment]
about max-31856 i just installed those 2 packs and service started, i don't have a 31856 (i thought have it, but not!).
i populated raspberry with a max31855 and a thermocouple, temp reading is ok, if i start a program should i see the timer running in real time?

**Comment by jbruce12000** [comment]
ok, I see what is happening. You are NOT running a simulation. You running a real kiln. You have the setting...

kiln_must_catch_up = True

Here is what that does...

# If the kiln cannot heat or cool fast enough and is off by more than
# kiln_must_catch_up_max_error  the entire schedule is shifted until
# the desired temperature is reached. If your kiln cannot attain the
# wanted temperature, the schedule will run forever. This is often used
# for heating as fast as possible in a section of a kiln schedule/profile.

So, very little time is passing (milliseconds) because that is what is expected. If you do not want this, set kiln_must_catch_up = False.

I'm gonna close this thread. open another with a specific bug if you find one. the initial problem of max-31856 library always being required has been fixed and committed to master.
